### ISSUE TITLE
Database settings on Drupal Config

### ISSUE THREAD

**Issue by hchoudhrydw** [RobLoach/drupal-fig#1]
Hi, I have installed and successfully started Durpal with docker however i am requested to enter the database details into the drupal install. I have tried what the readme file has suggested but to no avail, please can you advice.

**Comment by RobLoach** [comment]
username: drupal
password: drupal
database: drupal
host: database

**Comment by RobLoach** [comment]
@hchoudhrydw Did you get it working? I've updated the README.md a bit to detail those settings.

**Comment by RobLoach** [comment]
Closing for now. Let me know if you still have issues.
