### ISSUE TITLE
Drupal files are in /var/www/html/ so why is /app the working dir

### ISSUE THREAD

**Issue by abyshakes** [RobLoach/drupal-fig#10]
Drupal is in /var/www/html depending on which version of the image is installed.

**Comment by RobLoach** [comment]
With this workflow, it expects you to maintain your own Drupal code base at `docker-compose-drupal/drupal/*`.

Mounting /var/www/html locally on the host machine doesn't seem to work that well, unless they've updated it in Docker. Do you know a better way around it?

**Comment by abyshakes** [comment]
@RobLoach the docker image for Drupal (https://hub.docker.com/_/drupal/) has the distribution in the container at /var/www/html based on the tag. for eg 

`image: drupal:8-apache`

will also have apache on it.

Please check my fork, I can send a pull request but I think theres a better way to do it with drush in a separate container also linked.

**Comment by abyshakes** [comment]
K, after playing around I think this workflow works :) 👍
