### ISSUE TITLE
I'm unable to connect to the maria DB container

### ISSUE THREAD

**Issue by abyshakes** [RobLoach/drupal-fig#11]
I'm sending a pull request for this :)

**Comment by RobLoach** [comment]
It should be.... drupal:drupal@database/drupal

**Comment by abyshakes** [comment]
I was trying to connect using Sequel Pro

**Comment by RobLoach** [comment]
Gotcha! Is it working now?

**Comment by abyshakes** [comment]
Yup, its working. 👍
