### ISSUE TITLE
Workflow advice; saving containers, updating yml, etc.

### ISSUE THREAD

**Issue by mccrodp** [RobLoach/drupal-fig#4]
I have a few dev envs I'm moving from an old laptop over to a new one with Docker etc., hopefully all using this repo.

I will presumably use a separate instance of this repo per project. How do you advise saving out current state of a container to an image and updating the docker yml file.

I created a docker image of the mysql container and then update the yml to use it instead of the mysql:5.7 image, however it didn't seem to preserve the database I had and running `docker compose up` just created a fresh instance of what seemed to be `mysql:5.7` with the name of my new image.

Is there something "Docker Compose" specific needed here?

**Comment by mccrodp** [comment]
@RobLoach - I tried `docker-compose build` after creating an image from the _mysql_ container and updating the _docker_compose.yml_ and still it creates a container with no drupal database. 

Bit of confusion on this one unfortunately. At the moment I have to keep importing the DB into the container:

`docker exec -i dockercompose_mysql_1 mysql -udrupal -pdrupal drupal < /dev/docker-compose/databases/db_import.sql`

**Comment by RobLoach** [comment]
For importing? We should add some tools in there, Drupal Console, Drush, etc. Once you have `docker-compose up` running, it should be something like:

```
docker-compose run web drush status
```

**Comment by RobLoach** [comment]
Suggest trying out https://github.com/Wodby/docker4drupal
