### ISSUE TITLE
Missing PHP module / config? Image styles not generating in vanilla Drupal 7 setup

### ISSUE THREAD

**Issue by mccrodp** [RobLoach/drupal-fig#6]
It seems the default dev environment here does not allow for image style generation.

I'm seeing this on a few different environments with different Drupal 7 (7.40 - 7.42) sites now, image styles are not generated when they are flushed. Strange thing is that we don't see access errors in the "Drupal Reports" UI. Also, I have changed the permissions recursively to 777 on sites/default/files directory.

I'm wondering is it a missing php module or other image generation related include missing in the server config.

I'll update if I come across anything, but just logging this here in case anyone else sees the same.

I tried installing `imagemagick` and `php5-imagick` which is possibly part of the problem, but no luck.

**Comment by mccrodp** [comment]
Any ideas on this @RobLoach? Perhaps I should have posted this in the Dockie repo...

I'd like to stick with it and contribute to this repo, but I've no ideas what this image style generation issue could be after looking for a while (as mentioned here https://github.com/RobLoach/Dockie/issues/41). 

Obviously need styles generating for dev, so might have to jump ship over the next day or so unless I get this sorted soon :(

If you have this env handy and had a chance to take a look, or even just have any ideas, that'd be much appreciated, if not no worries.

**Comment by mccrodp** [comment]
I found that this was a docker permissions issue of some kind, when I cloned my repo on the host it didn't work and when I cloned my repo from within the container it did. Even though ownership and permissions looked the same on both.

**Comment by RobLoach** [comment]
Oh, interesting... Any way we could improve this? More documentation?

**Comment by mccrodp** [comment]
I found out what it was. User on host needs to be mapped to container www-data (e.g. for apache; see link to my repo). I [forked your repo](https://github.com/mccrodp/drupal-docker-compose/blob/master/Dockerfile) to give myself more control over tweaking things. Feel free to grab anything off that for yours. Many thanks for all your work / help.
