### ISSUE TITLE
Change image to dockie/drupal: Clean URLs issue with PHP inbuilt server

### ISSUE THREAD

**Issue by mccrodp** [RobLoach/drupal-fig#7]
For anyone using this repo:

Probably best to change the image for the web container to your "dockie/drupal" image in docker-compose.yml as PHP inbuilt server doesn't support clean urls:

https://www.drupal.org/node/1543858

**Comment by RobLoach** [comment]
Is dockie/drupal stable? I haven't tried it in a while. Thoughts? Anything we'd need to touch up in it?

**Comment by mccrodp** [comment]
Not sure Rob, stopped using it. There are the official Drupal images on docker now also with most of the necessary packages already installed. They may be a better starting point than a full debian build?!

**Comment by RobLoach** [comment]
Rolling with the official `drupal:8` now that it is up to speed.
